name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-6666d1aa5e18160001601c30-7d03b72bbc787d3b16fa8e9ff2d56c206b 
      - name: Run API tests
        run: |
          postman collection run "16548351-99544b00-a94d-4053-bed2-e305bdfe9691"
      - name: Install Newman and Allure Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-allure

      - name: Install OpenJDK
        run: |
          brew install openjdk@11
          echo 'export PATH="/usr/local/opt/openjdk@11/bin:$PATH"' >> ~/.zshrc
          echo 'export CPPFLAGS="-I/usr/local/opt/openjdk@11/include"' >> ~/.zshrc
          echo 'export JAVA_HOME=$(/usr/libexec/java_home -v 11)' >> ~/.zshrc
          source ~/.zshrc

      - name: Install Allure
        run: brew install allure

      - name: Run Newman
        run: newman run ./collection/dmoney-users.postman_collection.json -r allure

      - name: Generate Allure Report
        run: allure serve ./allure-results
          
