name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-6666d1aa5e18160001601c30-7d03b72bbc787d3b16fa8e9ff2d56c206b 
      - name: Run API tests
        run: |
          postman collection run "16548351-99544b00-a94d-4053-bed2-e305bdfe9691"
      - name: Install Newman and Allure Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Newman
        run: newman run ./collection/dmoney-users.postman_collection.json -r htmlextra
      - name: Run Newman
        run: newman run ./collection/dmoney-users.postman_collection.json -r htmlextra

     
